cupcat_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, increase_amount, decrease_amount, delete_product
from main.views import edit_product
from main.views import delete_product, get_product_json, add_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),

    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),

    path('increase-amount/<int:id>', increase_amount, name='increase_amount'),
    path('decrease-amount/<int:id>', decrease_amount, name='decrease_amount'),
    path('delete-product/<int:id>', delete_product, name='delete_product'),

    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    sweetness = models.IntegerField()
    amount = models.PositiveIntegerField()

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description","sweetness","amount"]

main/views.py
import json
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from django.shortcuts import render
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

# Create your views here.
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }
    
    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def increase_amount(request, id):
    product = Product.objects.get(pk=id)
    product.amount += 1
    product.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrease_amount(request, id):
    product = Product.objects.get(pk=id)
    if (product.amount - 1 >= 0):
        product.amount -= 1
        product.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_product(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        sweetness = request.POST.get("sweetness")
        amount = request.POST.get("amount")
        user = request.user

        new_product = Product(name=name, price=price, description=description,sweetness=sweetness, amount=amount,user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            sweetness = int(data["sweetness"]),
            amount = int(data["amount"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
        .container1{
            background-color: white;
            background: linear-gradient(to bottom, #EDEDFF, #FFAEAE);
            display: flex;
            flex-direction: column;
            padding:20px;
            gap:50px;
            align-items: center;
            width: 1480px;
            height: 770px; 
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background: linear-gradient(to bottom, #FFAE98, #FFD9AD);
            border-radius: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        .form-table {
            width: 100%;
        }
        .form-table th {
            text-align: left;
            padding: 10px;
        }
        .form-table td {
            padding: 10px;
        }
        .form-table input[type="text"],
        .form-table input[type="number"] {
            width: 100%;
            padding: 8px;
            background-color: #ffeae4;
            border: 1px solid pink;
            border-radius: 20px;
        }
        .form-table input[type="submit"] {
            background-color: #FFAE98;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
        }
        .form-table input[type="submit"]:hover {
            background-color: #BC5151;
        }

        .judul{
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1{
            background-color: #FFC0C0;
            font-size: 25px;
            font-weight: bold;
            font-family: 'Font Name', sans-serif;
            padding: 5px;
            display: flex;
            justify-content:center;
            width: 800px;
            border-radius: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container1">
        <h1>Add New Product</h1>

        <div class="container">
            <form method="POST" class="form-table">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Add Product"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
</div>
</body>
{% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

    <style> 
        .login-container{
            position: absolute;
            background-image: url('https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/Background%20Pas%20New.svg');
            background: linear-gradient(90deg, #FFF 0.19%, #FEF 93.27%);
            display: flex;
            flex-direction: column;
            gap:50px;
            align-items: center;
            width: 100% !important;
            height: 100%;
            margin: 0px;
        }

        .isi{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 500px;
            margin: 0;
            padding: 0;
        }

        .login_btn {
            width: 120px;
            height: 40px;
            border-radius: 10px;
            cursor: pointer;
            border: none;
            font-weight: bold;
            font-size: 16px;
            background: #FFDCDC;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            color:white;
        }
        
        .login_btn:hover {
            background-color: #FFA0A0;
        }

        .buttonRegister {
            display: inline-block;
            text-align: center;
            height:40px;
            width:140px;
            padding-top: 10px;
            background-color: #E49C9C; 
            color: white; 
            border: none; 
            border-radius: 5px; 
            text-decoration: none; 
            font-size: 14px; 
            font-weight: bold; 
            cursor: pointer;
            margin-right: 20px;
            margin-top: 10px;
            
        }
        
        .buttonRegister:hover {
            background-color: #BC5151; 
        }

        .navbar{
            position: sticky;
            top: 0;
            left: 0;
            width: 100%;
           
            
            background-color: #FFC0C0;
            font-size: 10px;
            font-weight: bold;
            font-family: 'Font Name', sans-serif;
            display: flex;
            flex-direction: row;
            background: radial-gradient(155.28% 155.28% at 50% -55.28%, #FFC1C1 0%, #FFF3E9 96.88%);
            box-shadow: 0px 4px 20px 0px rgba(0, 0, 0, 0.50);
            
          }

          .inputBar{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 500px;
            height: 300px;
            background-color: white;
            border-collapse: collapse;
            border-radius:40px;
            box-shadow: 4px 4px 20px 0px rgba(0, 0, 0, 0.25);
            text-align: center; /* Menyelaraskan konten secara horizontal ke tengah */
            vertical-align: middle;
            margin: 0; /* Menghapus margin */
            padding: 0;
          }

          .logo{
            justify-content: left;
            left:0;
            margin-right: 30px;

          }
          
          .form-control {
            width: 230px;
            height: 39px;
            flex-shrink: 0;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 30px;
            background: radial-gradient(155.28% 155.28% at 50% -55.28%, #FFC1C1 0%, #FFF3E9 96.88%);
            box-shadow: 4px 4px 20px 0px rgba(0, 0, 0, 0.25) inset;
        }

          .inputBar td {
            padding: 10px;
        }

        .container-meng{
            z-index: 1;
            display: flex;
            width: 500px;
            flex-direction: row;
            justify-content: right;
            margin-bottom: -5px;
        }

        .fotokucing td{
            padding:20px;
        }

        .logo {
            margin-left: 20px;
        }
    
    </style>

    <div class = "login-container">
        <div class="navbar">
            <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/logo%20cupcat.svg" class="logo"> 
            <a class = "buttonRegister" href="{% url 'main:register' %}"> Register Now</a> 
        </div>     
            <div class="isi">

                <div class="container-meng">
                    <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/Group%2013.svg" class="kucing-foto">
                </div>

                <form method="POST" action="">
                    {% csrf_token %}
                    <table class="inputBar">
                        
                        <tr>
                            <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                        </tr>
                                
                        <tr>
                            <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                        </tr>

                        <tr>
                            <td><input class="login_btn" type="submit" value="Login"></td>
                        </tr>
                    </table>
                </form>
            

                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}      
            </div>
        </div>

    </div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
  <head>
    <title>Welcome to Cupcat-Shop</title>
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      .main-container {
        position: relative;
        background-color: white;
        background: linear-gradient(to bottom, #dfdfff, #FFAEAE);
        display: flex;
        flex-direction: column;
        padding-top: 64px;
        gap: 50px;
        align-items: center;
        width: 100%;
        height: 100%;
        margin: 0px;
      }
      header {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        background-color: pink;
        padding: 10px 0;
        text-align: center;
        z-index: 1000;
        background-color: #FFC0C0;
        font-size: 25px;
        font-weight: bold;
        font-family: 'Font Name', sans-serif;
        display: flex;
        justify-content: center;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
      }
      th, td {
        border: 1px solid #ddd;

        padding: 20px;
        text-align: left;
      }
      tr:nth-child(odd) {
        background-color: white;
      }
      th {
        padding: 8px;
        background-color: #FFC0C0;
        font-weight: bold;
      }
      tr:nth-child(even) {
        background-color: #f2f2f2;
      }
      table {
        width: 80%;
        border-collapse: collapse;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
      }
      .buttonLogin {
        background-color: #E49C9C;
        width: 200px;
        height: 100px;
        border-radius: 10px;
        cursor: pointer;
      }
      .buttonLogin:hover {
        background-color: #BC5151;
      }
      .buttonLogindir {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 20px;
      }
      .textUpdate {
        font-size: 20px;
        font-weight: bold;
        font-family: 'Font Name', sans-serif;
      }
      .buttonSmall {
        background-color: #E49C9C;
        width: 75px;
        height: 25px;
        border-radius: 10px;
        cursor: pointer;
      }
      .custom-row.last-row td {
        background-color: #ff9999;
      }

      .btnajax {
        background-color: #E49C9C;
        width: 200px;
        height: 100px;
        border-radius: 10px;
        cursor: pointer;
      }
    </style>
  </head>

    <div class='main-container'>
      <header>
        /ᐠ. ｡.ᐟ\ᵐᵉᵒʷˎˊ˗ SELAMAT DATANG {{ name }} DI CUPCAT-SHOP /ᐠ. ｡.ᐟ\ᵐᵉᵒʷˎˊ˗
      </header>
      <p> Kamu memiliki stock {{ products.count }} cupcake pada toko ini</p>

      <table id="product_table"></table>
      <div class="buttondir">
        <h5>Sesi terakhir login: {{ last_login }}</h5>
        <a href="{% url 'main:logout' %}">
          <button class="buttonLogin">
            Logout
          </button>
        </a>
        <button type="button" class="btnajax" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
      </div>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="form" onsubmit="return false;">
              {% csrf_token %}
              <div class="mb-3">
                <label for="name" class="col-form-label">Name:</label>
                <input type="text" class="form-control" id="name" name="name">
              </div>
              <div class="mb-3">
                <label for="price" class="col-form-label">Price:</label>
                <input type="number" class="form-control" id="price" name="price">
              </div>
              <div class="mb-3">
                <label for="description" class="col-form-label">Description:</label>
                <textarea class="form-control" id="description" name="description"></textarea>
              </div>
              <div class="mb-3">
                <label for="sweetness" class="col-form-label">Sweetness:</label>
                <input type="number" class="form-control" id="sweetness" name="sweetness">
              </div>
              <div class="mb-3">
                <label for="amount" class="col-form-label">Amount:</label>
                <input type="number" class="form-control" id="amount" name="amount">
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
          </div>
        </div>
      </div>
    </div>
    
  </div>

  
  <script>
   async function getProducts() {
    return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
  }

  async function refreshProducts() {
    document.getElementById("product_table").innerHTML = "";
    const products = await getProducts();
    let htmlString = `<tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Sweetness</th>
        <th>Amount</th>
    </tr>`;
    products.forEach((item) => {
      htmlString += `\n<tr>
        <td>${item.fields.name}</td>
        <td>${item.fields.price}</td>
        <td>${item.fields.description}</td>
        <td>${item.fields.sweetness}</td>
        <td>${item.fields.amount}</td>
      </tr>`;
    });
    
    document.getElementById("product_table").innerHTML = htmlString;
  }

  refreshProducts();

  function addProduct() {
    fetch("{% url 'main:add_product_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
    }).then(refreshProducts);

    document.getElementById("form").reset();
    return false;
  }

  document.getElementById("button_add").onclick = addProduct;
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

    <style> 
        .login-container{
            position: absolute;
            background-image: url('https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/Background%20Pas%20New.svg');
            background: linear-gradient(90deg, #FFF 0.19%, #FEF 93.27%);
            display: flex;
            flex-direction: column;
            gap:50px;
            align-items: center;
            width: 100% !important;
            height: 100%;
            margin: 0px;
        }

        .isi{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 500px;
            margin: 0;
            padding: 0;
        }

        .login_btn {
            width: 120px;
            height: 40px;
            border-radius: 10px;
            cursor: pointer;
            border: none;
            font-weight: bold;
            font-size: 16px;
            background: #FFDCDC;
            box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
            color:white;
        }
        
        .login_btn:hover {
            background-color: #FFA0A0;
        }

        .buttonRegister {
            display: inline-block;
            text-align: center;
            height:60px;
            width:140px;
            padding-top: 10px;
            background-color: #E49C9C; 
            color: white; 
            border: none; 
            border-radius: 5px; 
            text-decoration: none; 
            font-size: 14px; 
            font-weight: bold; 
            cursor: pointer;
            margin-right: 20px;
            margin-top: 10px;
            
        }
        
        .buttonRegister:hover {
            background-color: #BC5151; 
        }

        .navbar{
            position: sticky;
            top: 0;
            left: 0;
            width: 100%;
           
            
            background-color: #FFC0C0;
            font-size: 10px;
            font-weight: bold;
            font-family: 'Font Name', sans-serif;
            display: flex;
            flex-direction: row;
            background: radial-gradient(155.28% 155.28% at 50% -55.28%, #FFC1C1 0%, #FFF3E9 96.88%);
            box-shadow: 0px 4px 20px 0px rgba(0, 0, 0, 0.50);
            
          }

          .inputBar{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 500px;
            height: 300px;
            background-color: white;
            border-collapse: collapse;
            border-radius:40px;
            box-shadow: 4px 4px 20px 0px rgba(0, 0, 0, 0.25);
            text-align: center; /* Menyelaraskan konten secara horizontal ke tengah */
            vertical-align: middle;
            margin: 0; /* Menghapus margin */
            padding: 0;
          }

          .logo{
            justify-content: left;
            left:0;
            margin-right: 30px;

          }
          
          .form-control {
            width: 230px;
            height: 39px;
            flex-shrink: 0;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 30px;
            background: radial-gradient(155.28% 155.28% at 50% -55.28%, #FFC1C1 0%, #FFF3E9 96.88%);
            box-shadow: 4px 4px 20px 0px rgba(0, 0, 0, 0.25) inset;
        }

          .inputBar td {
            padding: 10px;
        }

        .container-meng{
            z-index: 1;
            display: flex;
            width: 500px;
            flex-direction: row;
            justify-content: right;
            margin-bottom: -5px;
        }

        .fotokucing td{
            padding:20px;
        }

        .logo {
            margin-left: 20px;
        }
    
    </style>

    <div class = "login-container">
        <div class="navbar">
            <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/logo%20cupcat.svg" class="logo"> 
        </div>     
            <div class="isi">
                <div class="container-meng">
                    <img src="https://raw.githubusercontent.com/kayzaazr/cupcat-shop/main/gambar-website/Group%2013.svg" class="kucing-foto">
                </div>

                <form method="POST" action="">
                    {% csrf_token %}
                    <table class="inputBar">
                        
                        <tr>
                            <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                        </tr>
                                
                        <tr>
                            <td><input type="password" name="password1" placeholder="Password" class="form-control"></td>
                        </tr>

                        <tr>
                            <td><input type="password" name="password2" placeholder="Confirm Password" class="form-control"></td>
                        </tr>

                        <tr>
                            <td><input class="login_btn" type="submit" value="Daftar"></td>
                        </tr>
                    </table>
                </form>
            

                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}      
            </div>
        </div>

    </div>

{% endblock content %}